### ISSUE TITLE
Zorin 16.1 Pro, launching produces Parsing Errors

### ISSUE THREAD

**Issue by sootsnoot** [bluesabre/menulibre#100]
Just started using Zorin 16.1 Pro. Love it so far, still trying to get all my functionality over from Windows 10, so I can finally kiss Microsoft goodbye permanently.

There are programs I use all the time on Windows like Mozilla Thunderbird and Boxcryptor that actually run native on Linux. On Windows, I have them pinned to the taskbar, so I can easily launch them with  a single click. It seems that with Zorin, when you launch a program and its icon appears on the task bar, you can right-click the icon and select "Add to favorites"., and that makes them stay there after you exit the program, and then a single click will launch it again. But these particular programs are actually launched by bash scripts. I was able to use "System Tools" ->"Main Menu" to create new entries for them, so I can launch them by searching for them in the Zorin menu. But when they are running and their icons are on the task bar, right-clicking the icon doesn't offer an option to "Add to favorites".  It just offers options to Quit, and lists the open windows to let you choose which one to activate. When you quit the program, the icon disappears from the task bar.

Googling for creating launchers, I came across menulibre, so I installed it using the Zorin Software app. But when installation was complete and I clicked "Launch", a "Parsing Error" popped up, and clicking its "Details" button revealed the following. I have no idea what it means or what to do about it. Or even if there were no errors, would menulibre be useful in creating launchers at all, let alone ones that launch scripts that can be added to "Favorites". Just thought that I should be a good citizen and report the problem...

![Screenshot from 2022-06-12 22-44-12](https://user-images.githubusercontent.com/479141/173270327-2e9ddf1e-a910-4c2c-8020-262f1fc89f65.png)

**Comment by sootsnoot** [comment]
While the icon that shows up on the task bar when you run it from the Zorin menu does not offer an "Add to favorites" option when you right-click it, right-clicking the program directly in the Zorin menu does offer the option. So that problem is solved. And further reading suggests that the Main Menu app, used for customizing the main Zorin menu, creates launchers when you add items to it. And when you add an item, or modify one's properties, you can specify the icon to use. So it's not clear that menulibre would offer anything else that I'm looking for. Still thought you might be interested in the bug, though.

**Comment by bluesabre** [comment]
Thanks for the bug report. The error displayed means that the `fcitx-skin-installer.desktop` launcher is not correctly formatted. It appears to be provided by the `fcitx` package in the Ubuntu repositories.

https://bugs.launchpad.net/ubuntu/+source/fcitx

If you'd like, I would recommend reporting a bug against that package in Launchpad. However, since it's not really affecting you, there's not much reason to.
