### ISSUE TITLE
[help] Failed to execute command...

### ISSUE THREAD

**Issue by Atlaimond** [bluesabre/menulibre#101]
System: Linux Mint 20.3 (Xfce) 
MenuLibre: 2.2.1

Hello. 
I Wanted to create an another Libreoffice launcher, the command works 100% in terminal, but it fails to launch in MenuLibre saying: 

> **Failed to execute command "GTK_THEME=Mint-Y libreoffice".**
> Failed to execute child process "GTK_THEME=Mint-Y" (No such file or directory) 

I also tried to turn on the [Run in terminal] option. It also fails with a slightly different error message; 
> **Failed to execute child** 
>  Failed to execute child process "GTK_THEME=Mint-Y" (No such file or directory) 
 
This is where I've got stuck. 
My goal is to launch Libreoffice without terminal, in a different theme than my desktop has sat on, in order to create a workaround for this visual issue of dark theme with Libreoffice. 
Thank you for the help in advance. 

![Screenshot_2022-08-05_16-53-21](https://user-images.githubusercontent.com/75715297/183104901-39deba31-9e1b-4e4e-aedb-b33d57221dfc.png)

![Screenshot_2022-08-05_17-07-57](https://user-images.githubusercontent.com/75715297/183106287-4ae5d338-7687-4fcb-8be4-fda038a172aa.png)

**Comment by bluesabre** [comment]
Try using `env`. This is standard practice for launchers.

```
env GTK_THEME=Mint-Y libreoffice
```

**Comment by Atlaimond** [comment]
> Try using `env`. This is standard practice for launchers.
> 
> ```
> env GTK_THEME=Mint-Y libreoffice
> ```

`env` works perfectly! 😃️👍️ Thank you. 🙇‍♂️️
