### ISSUE TITLE
Application category icons are missing on Gnome 

### ISSUE THREAD

**Issue by samindaperamuna** [bluesabre/menulibre#145]
I am on Fedora 37 and Gnome 43.2. For some reason the application category icons are missing when using Adwaita icon theme (Default theme in Gnome)

![image](https://user-images.githubusercontent.com/16777956/216159843-42ab21e9-be43-42c3-8133-19c728b9bd60.png)

**Comment by cdock1029** [comment]
I'm seeing this still, just installed from flatpak (which is only at version 2.3.2 but after the fix in 2.3.1)
