### ISSUE TITLE
The GNOME 42 runtime is no longer supported

### ISSUE THREAD

**Issue by matfan73** [bluesabre/menulibre#150]
Flatpak, Ubuntu 22.04.2 LTS. 

When I try flatpak update:

«Info: org.gnome.Platform//42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.bluesabre.MenuLibre»
   
Thanks

**Comment by RDKRACZ** [comment]
https://github.com/flathub/org.bluesabre.MenuLibre/issues/6
