### ISSUE TITLE
Flatpak "The default menu could not be found."

### ISSUE THREAD

**Issue by Gersonzao** [bluesabre/menulibre#176]
- openSUSE Leap 15.5
- MenuLibre 2.2.3

Source, 2.3.1 tag and Leap repo's package (2.2.3) work fine

Screenshot:
![image](https://github.com/bluesabre/menulibre/assets/85644671/0c5d992a-e048-4732-ab65-f9d5fc4c99cd)

Diagnostics:
```
XDG_CURRENT_DESKTOP: XFCE
XDG_MENU_PREFIX: xfce-
DESKTOP_SESSION: xfce
KDE_SESSION_VERSION: None
MENUS: /app/etc/xdg/menus/gnome-applications.menu

**Comment by Gersonzao** [comment]
#1 duplicate

**Comment by kaizennet** [comment]
What is the correct solution to this? Experiencing the same issue on Debian 12.  There is a link to another case which links back to this case , neither of which offer a solution.  Although I could be missing something completely.
