### ISSUE TITLE
Add support for Gnome specific categories

### ISSUE THREAD

**Issue by philipzae** [bluesabre/menulibre#56]
Similar to the Xfce main category in the categories control, one should be added for Gnome, or maybe called DE-Specific, so it includes these Gnome specific categories and potentially non-Gnome specific ones as well.

X-GNOME-Settings-Panel
X-GNOME-PersonalSettings
X-GNOME-NetworkSettings
X-GNOME-Utilities

X-Unity-Settings-Panel

**Comment by bluesabre** [comment]
Thanks for the suggestion! Added in the above commit.
