### ISSUE TITLE
Gedit should be opened with root or sudo for files belonging to root.

### ISSUE THREAD

**Issue by stuaxo** [bluesabre/menulibre#62]
Use case:
- User has invalid desktop file owned by root.

Currently the user will click to edit the file, it will open in gedit and they cannot save it.

What should happen:   There should be a prompt to get root permissions and then gedit opened by root.

I'm not sure if there is a HIG / GNOME compliant way of doing the GUI for this, but if there is it should be followed.

**Comment by stuaxo** [comment]
Came back to report this, though maybe this should be something that Gedit itself can do TBH.

**Comment by stuaxo** [comment]
If it's a local file then it can be opened with admin `admin://` prefixed to it, and prompting will happen automatically.

**Comment by bluesabre** [comment]
@stuaxo I pushed a commit that should handle this scenario. Can you test it out?

**Comment by stuaxo** [comment]
I get password popup, but after I enter my password nothing happens.

In the log I can see this message:

```
(gedit:1131169): Gtk-WARNING **: 14:17:45.621: cannot open display: 
Unable to init server: Could not connect: Connection refused

(gedit:1132969): Gtk-WARNING **: 14:18:17.964: cannot open display: 
```

**Comment by TomaszGasior** [comment]
@bluesabre You should never open GUI apps as root, even through pkexec. This is insecure and unsupported in Wayland.  Instead, use admin:// protocol for editors like gedit (and forks, and maybe mousepad etc.). This works only with GIO/GVFS-based editors but root privileges are handled automatically and GUI is ran as current desktop user.

**Comment by bluesabre** [comment]
@stuaxo @TomaszGasior Thanks for the feedback. I just pushed up another change that should do the best-case scenario for supported editors. Tested with Gedit (admin:// supported), Pluma (admin:// supported), Mousepad (pkexec), and elementary Code (pkexec).
