### ISSUE TITLE
Problems starting menulibre in Debian Bullseye (Test) with xfce 4.14

### ISSUE THREAD

**Issue by Sorren1969** [bluesabre/menulibre#64]
Silently fails from the menu link.

Starting from CLI:

andrew@debian:$ apt list menulibre
Listing... Done
menulibre/testing,unstable,now 2.2.1-1 all [installed]
andrew@debian:$ menulibre

(menulibre:11060): Gtk-WARNING **: 17:24:04.224: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton

(menulibre:11060): Gtk-WARNING **: 17:24:04.308: gtk_menu_attach_to_widget(): menu already attached to GtkMenuButton
**
ERROR:gmenu-tree.c:3776:preprocess_layout_info: assertion failed: (!directory->preprocessed)
Bail out! ERROR:gmenu-tree.c:3776:preprocess_layout_info: assertion failed: (!directory->preprocessed)
Aborted

I have checked and all dependencies (listed on github page) are installed.

I couldn't find in Issues list, but found this: https://aur.archlinux.org/packages/menulibre/#comment-692215

Any ideas?

Thank you.

**Comment by bluesabre** [comment]
@Sorren1969 It seems like the gmenu library is struggling with your menus. Can you try the following:

- Try running alacarte to see if it has the same issue
- Run menulibre with verbose on (menulibre -vv) and capture the output

**Comment by AmberHaelo** [comment]
I get the exact same problem in Bullseye, and alacarte presents the exact same error message, so it looks like an issue in the gmenu-tree library itself.

**Comment by bluesabre** [comment]
Thanks for looking into this. I'm going to go ahead and close this issue out since the issue seems to be with gmenu instead of menulibre.
