### ISSUE TITLE
feature request(snap/flatpak)

### ISSUE THREAD

**Issue by Lvaskz** [bluesabre/menulibre#65]
Hi, see title above.

**Comment by TheEvilSkeleton** [comment]
I agree. I'd love to see this.

**Comment by TheEvilSkeleton** [comment]
@Lvaskz do you want to try to get Menulibre working as Flatpak?

**Comment by Lvaskz** [comment]
Hi, I am not developer, but I make flatPak app request, here you are in the right place to see menulibre as flatPak https://discourse.flathub.org/t/menulibre-request-flatpak/870

**Comment by TheEvilSkeleton** [comment]
Sorry for the late response. I haven't gotten any notifications from this.

**Comment by TheEvilSkeleton** [comment]
Okay, so I initialized the manifest: https://github.com/TheEvilSkeleton/flatpaks/blob/org.bluesabre.MenuLibre/org.bluesabre.MenuLibre.yaml

The program launched! Only thing I now have to do is try to get it to work, since it doesn't look through application files.

**Comment by TheEvilSkeleton** [comment]
@bluesabre I hope you don't mind the ping. Is there a way to make MenuLibre search inside `/run/host/` as well? Since flatpaks are completely sandboxed, host commands are unavailable inside the flatpak, they are mounted in `/run/host/`. For example, `/usr/bin/flatpak` in host will be in `/run/host/usr/bin/flatpak` inside the flatpak.

`/run/host/usr/bin/flatpak` cannot be executed, that's why I'd like to ask if it can just be found.

**Comment by Lvaskz** [comment]
Appeditor has the same problem, well I don't know if some other package as appimage or snap will be more convenient for that.

**Comment by TheEvilSkeleton** [comment]
Maybe a patch to check inside `/run/host/` as well? This is the only thing missing currently, since the program itself works, but it doesn't check host binaries.

**Comment by bluesabre** [comment]
@TheEvilSkeleton Sorry for the delay on this! I'll work on getting this added over the weekend.

**Comment by TheEvilSkeleton** [comment]
@bluesabre awesome. Just a little tip: you can fork my `flatpaks` repo and update the manifest, and then submit a merge request to https://github.com/flathub/flathub, since I've written most of the manifest already.

**Comment by bluesabre** [comment]
@TheEvilSkeleton @Lvaskz Thanks for the help here. I think I've got it all working with the below PR if you want to test it out.

https://github.com/bluesabre/menulibre/pull/73

**Comment by TheEvilSkeleton** [comment]
@bluesabre good news and bad news. The good news is that MenuLibre doesn''t complain about `flatpak` not being available:

![image](https://user-images.githubusercontent.com/50847364/108600452-45827200-7365-11eb-9e26-557a83ee8929.png)

The bad news is that the flatpaks don't show up in MenuLibre.

**Comment by TheEvilSkeleton** [comment]
@bluesabre I just tried to change a bit in the manifest, but all of them failed to see the Flatpak packages. I really don't know what to do now.

**Comment by bluesabre** [comment]
@TheEvilSkeleton I took another crack at it. However, I'm starting to get the feeling that the sandboxed nature of flatpaks is what's actually preventing them from being displayed. I also experimented with another flatpak'd app editor, but it doesn't list flatpaks either.

**Comment by TheEvilSkeleton** [comment]
@bluesabre I gave the Flatpak package rw access to `~/.local/share/flatpak/` (https://github.com/TheEvilSkeleton/flatpaks/blob/org.bluesabre.MenuLibre/org.bluesabre.MenuLibre.yaml#L14) and added it to the `XDG_DATA_DIRS` and `PATH`. That is all I can do to be honest. 

I guess the most we can do is ask help in #flatpak on freenode? I don't know how to code, so I cannot help much.

**Comment by Lvaskz** [comment]
Hi, 

> Appeditor has the same problem, well I don't know if some other package as appimage or snap will be more convenient for that.

here some information for changing mind. Appimage has not that issue, I guess
https://github.com/AppImageCrafters/appimage-builder

**Comment by TheEvilSkeleton** [comment]
@sonnyp you're a godsend, thanks a lot!

**Comment by sonnyp** [comment]
:blush: 

One thing I forgot to mention is that it would make menulibre even better as it will list apps with broken executables - allowing the user to delete or fix them.

**Comment by TheEvilSkeleton** [comment]
> One thing I forgot to mention is that it would make menulibre even better as it will list desktop entries with broken executables - allowing the user to delete or fix them.

Hmm... it only found some invalid desktop entries.

The rest seems to work well. I was able to edit apps without a problem and it does its job.

@bluesabre is it okay if I submit an MR in the Flathub repo so we can start making some bundles and test?

**Comment by bluesabre** [comment]
@TheEvilSkeleton Definitely, please do!

**Comment by sonnyp** [comment]
> Hmm... it only found some invalid desktop entries, not all of them.

You might want to patch further to disable checks for `OnlyShowIn` / `NotShowIn` / `NoDisplay` and `Hidden` but that's something else.

**Comment by TheEvilSkeleton** [comment]
> > Hmm... it only found some invalid desktop entries, not all of them.
> 
> You might want to patch further to disable checks for `OnlyShowIn` / `NotShowIn` / `NoDisplay` and `Hidden` but that's something else.

I confess, I'm not a programmer :sweat_smile: so I don't know what these are. I just enjoy creating Flatpak manifests.

**Comment by TheEvilSkeleton** [comment]
This can be closed: https://flathub.org/apps/details/org.bluesabre.MenuLibre!
