### ISSUE TITLE
Parsing error for `Type` value

### ISSUE THREAD

**Issue by rootkea** [bluesabre/menulibre#66]
Hello!

I'm using menulibre 2.2.1 on Ubuntu 20.04 LTS.

It seems that menulibre doesn't recognize `Service` as a valid `Type` value since it shows following parsing error:  

    Type value is invalid - currently 'Service', should be 'Application'

But as per the [desktop entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/apb.html), `Service` is a valid type along with other 2 types mentioned there.

Kdeconnect uses [.desktop file](https://invent.kde.org/network/kdeconnect-kde/-/blob/master/data/org.kde.kdeconnect_open.desktop#L106) with `Type=Service`.

Also, what about [`Link` (type 2) and `Directory` (type 3)](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html)? With current implementation, Libremenu will report the parsing error for .desktop files with `Type=Link` or `Type=Directory` - both valid type values.

Looks like this is the line of code in question:
https://github.com/bluesabre/menulibre/blob/c617e6bb49c2744904b4c6af3db1ad62dbdb15a0/menulibre/util.py#L647

Thanks!

**Comment by bluesabre** [comment]
Thanks for the bug report! Corrected in the above commit.
