### ISSUE TITLE
ModuleNotFoundError: No module named util

### ISSUE THREAD

**Issue by iadegesso** [bluesabre/menulibre#82]
According to the Gentoo bug tracker, I cannot build MenuLibre anymore since I installed GNOME 40.x and GTK+ 4.x, and I'm on GCC 10.x.

https://bugs.gentoo.org/787863

Regards,

Iade Gesso, MSc, PhD (in Computer Science)

**Comment by bluesabre** [comment]
With these two commits, the downstream patches are now included. This issue should now be resolved.

- https://github.com/bluesabre/menulibre/commit/c135a478bd9db5cac8f0efde50144e72f0697ef0
- https://github.com/bluesabre/menulibre/commit/f525b00b6b67c24b6894561abc54d7b47096bfca
