### ISSUE TITLE
Where does it store its settings?

### ISSUE THREAD

**Issue by tio-trom** [bluesabre/menulibre#84]
I am using this with XFCE and I'd like to port the changes I make to the Wisker menu to another system. But where can I find the settings (config files)? Thanks!

**Comment by bluesabre** [comment]
I believe the three directories you need are:

- `~/.config/menus` (contains the menu layout files)
- `~/.local/share/applications` (contains application launchers)
- `~/.local/share/desktop-directories` (contains the menu subdirectories)

**Comment by tio-trom** [comment]
Awesome. It works! Thank you very much!
