### ISSUE TITLE
appdata file is installed twice

### ISSUE THREAD

**Issue by algent-al** [bluesabre/menulibre#85]
Hi!

Thank you for releasing a new version of menulibre.

Just installed this for Solus, and I notice that `menulibre.appdata.xml` is installed twice.

```
/usr/share/menulibre/metainfo/menulibre.appdata.xml.in
/usr/share/metainfo/menulibre.appdata.xml
```
I guess this file `menulibre.appdata.xml.in` isn't neccessary.

**Comment by bluesabre** [comment]
This should be resolved with the above commit.
