### ISSUE TITLE
dclock with -date "%a %Y-%m-%d"  doesn't work

### ISSUE THREAD

**Issue by garrytre** [bluesabre/menulibre#93]
Hi
I'm trying to use start
dclock -miltime -noblink  -seconds -date "%a %Y-%m-%d"

That works from xterm, but from MenuLibre the -date "%a %Y-%m-%d" part doesn't work - I just get 2 hyphens where the date should be.

Otherwise dclock -miltime -noblink  -seconds    works from MenuLibre

xubuntu 20.04.3 LTS (Focal Fossa)

Any ideas?

thaanks

**Comment by bluesabre** [comment]
It looks like the arguments need to be escaped with an additional `%` character. I've applied a change to MenuLibre to do this automatically as of the next release.
