### ISSUE TITLE
Editing system default menu

### ISSUE THREAD

**Issue by elig0n** [bluesabre/menulibre#94]
since running as root is problematic can this app be used to modify the built-in system menus ? i.e. /usr/share/applications

**Comment by mrEDitor** [comment]
Yes, application copies global desktop file to local one and then modify it, works OK — according https://wiki.archlinux.org/title/desktop_entries#Application_entry. But on my Archlinux machine it seems to work only with menulibre installed from https://aur.archlinux.org/packages/menulibre-git not from https://flathub.org/apps/details/org.bluesabre.MenuLibre (is it just out-of-date?)

**Comment by bluesabre** [comment]
That's correct. The Flathub version of MenuLibre isn't fully functional yet.
